use_bias: true

archs:
  - _target_: metanca.nn.MultiLayerPerceptron
    layer_specs: [3]
    activation: leaky_relu
    final_layer_activation: identity
    use_bias: ${model.use_bias}
  - _target_: metanca.nn.MultiLayerPerceptron
    layer_specs: [10, 3]
    activation: leaky_relu
    final_layer_activation: identity
    use_bias: ${model.use_bias}
  - _target_: metanca.nn.MultiLayerPerceptron
    layer_specs: [5, 10, 3]
    activation: leaky_relu
    final_layer_activation: identity
    use_bias: ${model.use_bias}
  - _target_: metanca.nn.MultiLayerPerceptron
    layer_specs: [20, 3]
    activation: leaky_relu
    final_layer_activation: identity
    use_bias: ${model.use_bias}

test_arch:
  _target_: metanca.nn.MultiLayerPerceptron
  layer_specs: [10, 5, 3]
  activation: leaky_relu
  final_layer_activation: identity
  use_bias: ${model.use_bias}
