archs:
  - _target_: metanca.nn.ResNet
    num_classes: 10
    stage_blocks: [1, 1, 1]
    use_bn: false
    base_channels: 16
    act: relu

  - _target_: metanca.nn.ResNet
    num_classes: 10
    stage_blocks: [1, 1, 1]
    use_bn: false
    base_channels: 20
    act: relu


test_arch:
  _target_: metanca.nn.ResNet
  num_classes: 10
  stage_blocks: [1, 1, 1]
  use_bn: false
  base_channels: 18
  act: relu
